version: '3'
services:
  broker:
    image: ghcr.io/d8-x/d8x-broker-server:dev
    restart: always
    depends_on:
      - redis
    ports:
      # Default svc port is 8000
      - 127.0.0.1:8000:8000
    environment:
      REDIS_ADDR: "${REDIS_ADDR}"
      REDIS_PW: "${REDIS_PW}"
      BROKER_KEY: "${BROKER_KEY}"
      BROKER_FEE_TBPS: "${BROKER_FEE_TBPS}"
      CONFIG_PATH: /chain_config
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    configs:
      - chain_config

  executorws:
    image: ghcr.io/d8-x/d8x-broker-exec-ws:dev
    restart: always
    depends_on:
      - redis
    ports:
      # Default svc port is 8080
      - 127.0.0.1:8080:8080
    environment:
      REDIS_ADDR: "${REDIS_ADDR}"
      REDIS_PW: "${REDIS_PW}"
      WS_ADDR: "${WS_ADDR}"
      BROKER_KEY: "${BROKER_KEY}"
      BROKER_FEE_TBPS: "${BROKER_FEE_TBPS}"
      CONFIG_PATH: /chain_config
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    configs:
      - chain_config

  redis:
    image: redis/redis-stack-server:latest
    command: redis-stack-server --requirepass ${REDIS_PW}
    environment:
      - TZ=UTC
    ports:
      - "6379:6379"
    networks:
      - app-net
    restart: on-failure
    logging:
      options:
        max-size: "10m"
        max-file: "10"

networks:
  app-net:

configs:
  chain_config:
    file: ./config/chainConfig.json