name: Build images
on:
  push:
    branches: ["main", "dev"]
    tags:
      # Build images for all tags
      - "*"
env:
  container_registry: ghcr.io
jobs:
  build:
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./cmd/Dockerfile
            image: ghcr.io/d8-x/d8x-broker-server
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.container_registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Add SSH Private key for d8x-futures go sdk private repo
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
          ssh-add - <<< "${{ secrets.D8X_FUTURES_REPO_PRIVATE_KEY }}"
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV        
      - name: Setup access for private go modules
        run: |
            git config --global url."ssh://git@github.com/".insteadOf https://github.com/
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{matrix.image}}
      - name: Build and push ${{ matrix.image }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            - GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - GITHUB_USER: ${{ github.actor }}
